const videoTitle = "How to Create Eye-Catching YouTube Thumbnails"
const channelName = "Thumbnail Tester"

export const sampleVideos = [
  {
    id: 1,
    title: videoTitle,
    channel: channelName,
    views: "12K",
    time: "2 days ago",
    duration: "10:24",
    thumbnail: "/placeholder.svg?height=180&width=320&text=Design+Tutorial",
    isUserVideo: "A",
    description:
      "With this comprehensive tutorial, you can easily and securely create eye-catching thumbnails using your favorite design tools. We'll show you how to...",
    verified: true,
    avatar: "/avatar.jpg",
  },
  {
    id: 101,
    title: videoTitle,
    channel: channelName,
    views: "12K",
    time: "5 months ago",
    duration: "15:48",
    thumbnail: "/thumbnail-B.webp",
    isUserVideo: "B",
    description:
      "Second user thumbnail for comparison.",
    verified: true,
    avatar: "/avatar.jpg",
  },
  {
    id: 2,
    title: "Protect $500,000 Keep It!",
    channel: "MrBeast",
    views: "178M",
    time: "1 year ago",
    duration: "15:34",
    thumbnail: "/mrbeast-video-1-thumbnail-tester.webp",
    description:
      "He spent so much money lol. Grow your money with the Mighty Oak debit card from Acorns. Sign up at ",
    verified: true,
    avatar: "/MrBeast.jpg",
  },
  {
    id: 3,
    title: "$1 vs $1,000,000,000 Yacht!",
    channel: "MrBeast",
    views: "475M",
    time: "2 days ago",
    duration: "14:47",
    thumbnail: "/mrbeast-video-2-thumbnail-tester.webp",
    description:
      "Buy Feastables anywhere to get a secret MrBeast video: https://bit.ly/_feastables, Go watch Pete Davidson's new show Bupkis now live on Peacock!Check out the all new Icon of the Seas coming 2024",
    verified: false,
    avatar: "/MrBeast.jpg",
  },
  {
    id: 4,
    title: "Technical SEO for Developers | 17 Tips to Rank Higher!",
    channel: "Prismic",
    views: "18K",
    time: "8 months ago",
    duration: "21:54",
    thumbnail: "/Prismic-thumbnail.webp",
    description:
      "What if you had the best website in the world, but no one could see it? This is where technical SEO comes in. By implementing best practices on your website, you can ensure that Google indexes it properly and doesn't penalize it. ",
    verified: false,
    avatar: "/Prismic-avatar.jpg",
  },
  {
    id: 5,
    title: "The Side of China The Media Won't Show You",
    channel: "Mike Okay",
    views: "11M",
    time: "9 months ago",
    duration: "50:14",
    thumbnail: "/mike-okay-thumbnail-tester.webp",
    description:
      "In this video I'll attempt to travel over 2000km across China. Nothing could have prepared me for what was to come on this journey.enjoy, mike x--------My Previous Videos in this series:",
    verified: true,
    avatar: "/mike-okay-avatar.jpg",
  },
  {
    id: 6,
    title: "SHROUD RECRUITS THE BEST FPS GAMERS FOR FRAGPUNK",
    channel: "shroud",
    views: "221K",
    time: "3 months ago",
    duration: "18:46",
    thumbnail: "/shroud-thumbnail.webp",
    description:
      "Shroud plays fragpunk with summit1g, tenz, itztimmy, fl0m, myth, squeex, 39daph, sacriel & sydeon. SECRET PROMO CODE ON ALL LOGITECH PRODUCTS: shroud",
    verified: false,
    avatar: "/shroud-avatar.jpg",
  },
  {
    id: 7,
    title: "Inflation Explained with Bananas",
    channel: "Primate Economics",
    views: "1.3M",
    time: "3 months ago",
    duration: "2:31",
    thumbnail: "/Primate-Economics-thumbnail.webp",
    description:
      "Monkey hope you understand inflation now. I'm planning on making more videos explaining complex financials with bananas. Who knows, maybe in the future I'll make enough from this to donate to endangered apes. That'd be pretty cool but we'll see how we go.",
    verified: false,
    avatar: "/Primate-Economics-avatar.jpg",
  },
  {
    id: 8,
    title: "AI Influencers Are Making Over $10,000 Per Month…Let’s Build One",
    channel: "David Bombardo",
    views: "977K",
    time: "1 year ago",
    duration: "9:57",
    thumbnail: "/david-bombardo-thumbnail.webp",
    description:
      "Get your Influencer and start making money today. Leonardo AI: https://app.leonardo.ai/?via=david-bo..., GitHub (Face Swap Bot): https://github.com/deepinsight/insigh...",
    verified: false,
    avatar: "/david-bombardo-avatar.jpg",
  },
  {
    id: 9,
    title: "$1 vs $1,000,000 Hotel Room!",
    channel: "MrBeast",
    views: "404M",
    time: "2 days ago",
    duration: "15:40",
    thumbnail: "/mrbeast-video-3.webp",
    description:
      "The hotel at the end is worth the wait! Results will vary. Not all payments are boost-eligible or considered by lenders. Credit Card offers are not available in all states. See website for details.",
    verified: true,
    avatar: "/MrBeast.jpg",
  },
  {
    id: 10,
    title: "NEURAL NETWORKS will enslave us by 2035, the future of neural networks",
    channel: "Igor Satorin",
    views: "418",
    time: "11 hours ago",
    duration: "10:54",
    thumbnail: "/Igor-Satorin-thumbnail.webp",
    description:
      "How this content was made. Auto-dubbed, Audio tracks for some languages were automatically generated. Learn more ",
    verified: false,
    avatar: "/Igor-Satorin-avatar.jpg",
  },
  {
    id: 11,
    title: "Timeless | Squid Game Season 2 [Edit] 4K",
    channel: "sanchezae",
    views: "985K",
    time: "5 months ago",
    duration: "00:39",
    thumbnail: "/sanchezae-thumbnail.webp",
    description:
      "Discover the secrets to successful live streaming. From technical setup to audience engagement, learn everything you need to know...",
    verified: true,
    avatar: "/sanchezae-avatar.jpg",
  },
  {
    id: 12,
    title: "Wednesday: Season 2 | Official Trailer | Netflix",
    channel: "Netflix",
    views: "2.4M",
    time: "11 hours ago",
    duration: "2:13",
    thumbnail: "/netflix-thumbnail-tester.webp",
    description:
      "Here we woe again. Watch the official trailer for Wednesday Season 2. Part 1 is coming on August 6th. Part 2 is coming on September 3rd. Only on Netflix.Watch on Netflix: https://www.netflix.com/title/81435630",
    verified: true,
    avatar: "/netflix-avatar.jpg",
  }
]